<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-10-21T11:25:15Z" name="Default suite" finished-at="2019-10-21T11:25:42Z" duration-ms="27519">
    <groups>
    </groups>
    <test started-at="2019-10-21T11:25:15Z" name="Default test" finished-at="2019-10-21T11:25:42Z" duration-ms="27519">
      <class name="com.TestCases.Testcase_2">
        <test-method is-config="true" signature="testsite()[pri:0, instance:com.TestCases.Testcase_2@7f132176]" started-at="2019-10-21T11:25:14Z" name="testsite" finished-at="2019-10-21T11:25:15Z" duration-ms="694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testsite -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.TestCases.Testcase_2@7f132176]" started-at="2019-10-21T11:25:15Z" name="launchBrowser" finished-at="2019-10-21T11:25:38Z" duration-ms="22662" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="login(java.util.Hashtable)[pri:0, instance:com.TestCases.Testcase_2@7f132176]" started-at="2019-10-21T11:25:38Z" name="login" data-provider="Data_Collections" finished-at="2019-10-21T11:25:38Z" duration-ms="68" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Email_id=neheshsakp23@gmail.com, Iteration=1.0, Company_Name=Wipro, First_Name=neha, Last_Name=parab}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [actiTIME - Time Tracking Software for Boosting Your Business] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [actiTIME - Time Tracking Software for Boosting Your Business] but found [actiTIME - Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Pages.Actitime_home_page.createAnTask(Actitime_home_page.java:16)
at com.TestCases.Testcase_2.login(Testcase_2.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="close()[pri:0, instance:com.TestCases.Testcase_2@7f132176]" started-at="2019-10-21T11:25:38Z" name="close" finished-at="2019-10-21T11:25:42Z" duration-ms="4682" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="writeToExtentReport()[pri:0, instance:com.TestCases.Testcase_2@7f132176]" started-at="2019-10-21T11:25:43Z" name="writeToExtentReport" finished-at="2019-10-21T11:25:44Z" duration-ms="822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeToExtentReport -->
      </class> <!-- com.TestCases.Testcase_2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
